<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Default.aspx.cs" Inherits="AWS_Kinesis_POC.Default" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>AWS KVS Example</title>
    <!-- Video JS -->
    <link rel="stylesheet" href="https://vjs.zencdn.net/6.6.3/video-js.css" />
    <script src="https://vjs.zencdn.net/6.6.3/video.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/videojs-contrib-hls/5.14.1/videojs-contrib-hls.js"></script>
    
    <!-- Bootstrap V5.0 -->
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>


    <script src="Scripts/jquery-1.6.4.min.js"></script>
    <script src="Scripts/jquery.signalR-2.4.2.min.js"></script>
    <!--Reference the autogenerated SignalR hub script. -->  
    <script src="/signalr/hubs"></script>  

</head>
<body>
    <script type="text/javascript">  

        $(function () {  
            // Declare a proxy to reference the hub.  
            var notification = $.connection.notyHub;  
            notification.client.broadcastMessage = function (value, islive) {  
                //alert(value);
                $("#streamName").html(value + (islive == true?'is now ONLINE': 'is now OFFLINE'));
                $("#toastDate").html(new Date().toLocaleTimeString());
                if(islive == true)
                    $("#liveToast").removeClass('bg-danger').addClass('bg-success');
                else
                    $("#liveToast").removeClass('bg-success').addClass('bg-danger');
                var myToastEl = document.getElementById('liveToast');
                var myToast = new bootstrap.Toast(myToastEl, {autohide: false});
                myToast.show();
            };  
         
            $.connection.hub.start().done(function () {  
            //send, the same method that we have in our chathub class  
                //notification.server.send("StreamName");  
            });  
        });  

    </script> 
    <form id="form1" runat="server">
        
        <div class="container-fluid">
            <nav class="navbar navbar-dark bg-dark mb-3">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Amazon Kinesis Video Streams Media Viewer in .Net</a>
    </div>
  </nav>
            <div class="main">
            <div class="row">
                <div class="col-3 gx-5">
                    
                    <h6>1. Connect to AWS.</h6>
                    <div class="card bg-light p-2">
                    <div class="mb-3">
                            <label>Region</label>
                            <asp:DropDownList runat="server" id="DDL_Region" class="form-control form-control-sm">
                            </asp:DropDownList>
                        </div>
                        <div class="mb-3">    
                        <label>AWS Access Key</label>
                            <asp:TextBox runat="server" id="TB_AccessKeyId" type="password" class="form-control form-control-sm"/>
                        </div>
                        <div class="mb-3">
                            <label>AWS Secret Key</label>
                            <asp:TextBox runat="server" id="TB_SecretAccessKey" type="password" class="form-control form-control-sm"/>
                        </div>
                        <div class="mb-3">
                            <label>AWS Session Token (Optional)</label>
                            <asp:TextBox runat="server" id="TB_SessionToken" type="password" class="form-control form-control-sm" />
                        </div>
                   </div>
                        <asp:Button runat="server" ID="BTN_FetchStreams" Text="Connect and Fetch Streams" OnClick="BTN_FetchStreams_Click" CssClass=" btn btn-primary mb-5"  style="margin-top:10px;"/>
                   
                    
                    <h6>2. Click on a Stream to select.</h6>    
                    <div class="card bg-light" style="height:300px;" >
                   
                    <ul class="list-group overflow-scroll">
                        <asp:Repeater runat="server" DataSource="<%# Streams %>" ID="RepStreams">
                            <ItemTemplate>
                                <asp:LinkButton runat="server" Text="<%# GetDataItem() %>" OnCommand="LBDescribeStream_Command" CommandArgument="<%# GetDataItem() %>" CssClass="list-group-item list-group-item-action" ID="LBPlayLive"></asp:LinkButton>

                            </ItemTemplate>
                        </asp:Repeater>
                    </ul>
                        </div>
                    <div class="input-group">
                        <asp:TextBox runat="server" ID="TB_StreamName" placeholder="Enter Stream Name" CssClass="form-control form-control-sm"></asp:TextBox>
                        <asp:Button runat="server" ID="BT_CreateStream" OnClick="BT_CreateStream_Click" CssClass="btn btn-outline-secondary" Text="Create Stream" />
                    </div>

                </div>
                <div class="col-3">
                    <h6>3. Configure Playback Options</h6>
                    <div class="card bg-light p-2 mb-2">
                    <div class="mb-3">
                            <label>Playback Mode</label>
                        <asp:DropDownList runat="server" ID="DDL_PlaybackMode" CssClass="form-control form-control-sm">
                            <asp:ListItem Text="Live" Value="LIVE" Selected="True"></asp:ListItem>
                            <asp:ListItem Text="Live Replay" Value="LIVE_REPLAY"></asp:ListItem>
                            <asp:ListItem Text="On Demand" Value="ON_DEMAND"></asp:ListItem>
                        </asp:DropDownList>
                        </div>
                        <div class="mb-3">
                            <label>Start Timestamp</label>
                            <asp:TextBox TextMode="DateTimeLocal" runat="server" ID="TB_st" CssClass="form-control form-control-sm"></asp:TextBox>
                        </div>
                        <div class="mb-3">
                            <label>End Timestamp</label>
                            <asp:TextBox TextMode="DateTimeLocal" runat="server" ID="TB_et" CssClass="form-control form-control-sm"></asp:TextBox>
                        </div>
                        <div class="mb-3">
                            <label>Fragment Selector Type</label>
                            <asp:DropDownList runat="server" id="DDL_FragmentSelectorType" class="form-control form-control-sm">
                                <asp:ListItem Value="SERVER_TIMESTAMP">SERVER_TIMESTAMP</asp:ListItem>
                                <asp:ListItem Value="PRODUCER_TIMESTAMP">PRODUCER_TIMESTAMP</asp:ListItem>
                            </asp:DropDownList>
                        </div>
                        <div class="mb-3">
                            <label>Container Format</label>
                            <asp:DropDownList runat="server" id="DDL_ContainerFormat" class="form-control form-control-sm">
                                <asp:ListItem Value="FRAGMENTED_MP4">FRAGMENTED_MP4</asp:ListItem>
                                <asp:ListItem Value="MPEG_TS">MPEG_TS</asp:ListItem>
                            </asp:DropDownList>
                        </div>
                        <div class="mb-3">
                            <label>Discontinuity Mode</label>
                            <asp:DropDownList runat="server" id="DDL_DiscontinuityMode" class="form-control form-control-sm">
                                <asp:ListItem Value="ALWAYS">ALWAYS</asp:ListItem>
                                <asp:ListItem Value="NEVER">NEVER</asp:ListItem>
                                <asp:ListItem Value="ON_DISCONTINUITY">ON_DISCONTINUITY</asp:ListItem>
                            </asp:DropDownList>
                        </div>
                        <div class="mb-3">
                            <label>Display Fragment Timestamp</label>
                            <asp:DropDownList runat="server" id="DDL_DisplayFragmentTimestamp" class="form-control form-control-sm">
                                <asp:ListItem Value="ALWAYS">ALWAYS</asp:ListItem>
                                <asp:ListItem Value="NEVER">NEVER</asp:ListItem>
                            </asp:DropDownList>
                        </div>
                        <div class="mb-3">
                            <label>Display Fragment Number</label>
                            <asp:DropDownList runat="server" id="DDL_DisplayFragmentNumber" class="form-control form-control-sm">
                                <asp:ListItem Value="ALWAYS">ALWAYS</asp:ListItem>
                                <asp:ListItem Value="NEVER">NEVER</asp:ListItem>
                            </asp:DropDownList>
                        </div>
                        <div class="mb-3">
                            <label>Max Manifest/Playlist Fragment Results</label>
                            <asp:TextBox runat="server" id="TB_MaxResults" type="text" class="form-control form-control-sm"/>
                        </div>
                        <div class="mb-3">
                            <label>Expires (seconds)</label>
                            <asp:TextBox runat="server" id="TB_Expires" type="text" TextMode="Number" class="form-control form-control-sm"/>
                        </div>
                    </div>
                     <asp:Button runat="server" ID="BTN_playArchive" Text="Play Stream" OnClick="BTN_playStream_Click" CssClass="btn btn-primary" />
                        
                            <asp:Button runat="server" ID="BTN_GetClip" Text="Get Clip" OnClick="BTN_GetClip_Click" CssClass="btn btn-primary" />
                </div>
                <div class="col-6 gx-5">
                    <div class="card bg-light">
                        <asp:Label runat="server" ID="LBL_Details"></asp:Label>
                    </div>
                    <div class="row justify-content-center align-items-center">
                        <div>
                            <br />
                            <video runat="server" id="JsPlayer" class="video-js vjs-default-skin vjs-big-play-centered" style="display: block; margin: 0 auto;" autoplay="autoplay" controls="controls" preload="none" height="480" width="720" data-setup='{"techOrder": ["flash", "nativeControlsForTouch": true, "progressControl": false } }'>
                                <source id="source" runat="server" type="application/x-mpegURL" />
                            </video>
                        </div>
                    </div>
                    <h4 style="margin-top: 20px;">Logs</h4>
                        <div class="card bg-light mb-3 overflow-auto" style="height:150px;">
                            <asp:Label runat="server" id="PNL_Logs" class="card-body text-monospace" style="font-family: monospace; white-space: pre-wrap;"></asp:Label>
                        </div> 
                </div>
            </div>
            </div>


            <div class="position-fixed top-0 end-0 p-3" style="z-index: 11">
          <div id="liveToast" class="toast hide bg-success" role="alert" aria-live="assertive" aria-atomic="true">
            <div class="toast-header">
              <i class="bi bi-cast me-2" style="font-size: 1.5rem; color: darkgreen"></i>
              <strong class="me-auto">AWS Kinesis</strong>
              <small><span id="toastDate"></span> </small>
              <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
            </div>
            <div class="toast-body text-white">
              <span id="streamName" ></span>.
            </div>
          </div>
        </div>
        </div>

        
    </form>
</body>
</html>

